version: "3.9"

services:
  postgres_user_db:
    image: postgres:15
    container_name: postgres_user_db
    restart: always
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_user_data:/var/lib/postgresql/data

volumes:
  pg_user_data:
